In [1]:
import pandas as pd
import numpy as np
import sklearn

In [2]:
df=pd.read_csv(r'D:\Machine Learning\Machine-Learning\Data\customer.csv')
df.head()

age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [3]:
df=df.iloc[:,2:]
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

# Ordinal Encoding

Ordinal encoding is a method of converting categorical data into numerical format while preserving the ordinal relationship between categories. This technique is suitable for categorical variables where the categories have a meaningful order or ranking. Unlike nominal encoding, ordinal encoding assigns numerical values to categories based on their order.

In [4]:
from sklearn.model_selection import train_test_split

# Assuming 'df' is your DataFrame with features and target variable
X = df.iloc[:, :-1]  # Features (all columns except the last one)
y = df.iloc[:, -1]   # Target variable (last column)

# Split the data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
x_train.shape,x_test.shape 

((40, 2), (10, 2))

In [5]:
from sklearn.preprocessing import OrdinalEncoder

# Defining ordinal mapping
oe=OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])
oe.fit(x_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [6]:
x_train=oe.transform(x_train)
x_train

array([[0., 0.],
       [1., 1.],
       [1., 2.],
       [1., 1.],
       [2., 2.],
       [2., 0.],
       [2., 2.],
       [0., 2.],
       [2., 2.],
       [0., 1.],
       [2., 1.],
       [0., 1.],
       [1., 2.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 1.],
       [0., 2.],
       [2., 2.],
       [1., 0.],
       [1., 1.],
       [2., 1.],
       [2., 1.],
       [0., 1.],
       [1., 2.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [2., 0.],
       [2., 0.],
       [2., 1.],
       [0., 2.],
       [2., 0.],
       [2., 1.],
       [1., 0.],
       [0., 0.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [2., 0.]])

In [7]:
x_test=oe.transform(x_test)
x_test

array([[1., 0.],
       [0., 2.],
       [1., 1.],
       [0., 2.],
       [0., 1.],
       [2., 1.],
       [0., 2.],
       [2., 0.],
       [1., 1.],
       [0., 2.]])

# Label Encoding - Target Variable

Label encoding is a method of converting categorical data into numerical format by assigning a unique integer to each category. This technique is suitable for nominal data, where the categories have no inherent order. Each category is represented by a distinct integer, allowing machine learning algorithms to work with categorical variables.

In [8]:
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()
le.fit(y_train)

LabelEncoder()

In [9]:
y_train=le.transform(y_train)
y_train

array([0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0])

In [10]:
y_test=le.transform(y_test)
y_test

array([0, 0, 0, 1, 1, 1, 0, 0, 1, 1])